package Datos;
// Generated 02/07/2022 0:41:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,catalog="sgjn"
)
public class Categoria  implements java.io.Serializable {


     private int idcategoria;
     private String nombre;

    public Categoria() {
    }

    public Categoria(int idcategoria, String nombre) {
       this.idcategoria = idcategoria;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="idcategoria", unique=true, nullable=false)
    public int getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


