package Datos;
// Generated 02/07/2022 0:41:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FacCab generated by hbm2java
 */
@Entity
@Table(name="fac_cab"
    ,catalog="sgjn"
)
public class FacCab  implements java.io.Serializable {


     private int idfacCab;
     private String fecha;
     private int idCliente;
     private String subtotal;
     private String desceunto;
     private String iva;
     private String total;
     private String observacion;

    public FacCab() {
    }

    public FacCab(int idfacCab, String fecha, int idCliente, String subtotal, String desceunto, String iva, String total, String observacion) {
       this.idfacCab = idfacCab;
       this.fecha = fecha;
       this.idCliente = idCliente;
       this.subtotal = subtotal;
       this.desceunto = desceunto;
       this.iva = iva;
       this.total = total;
       this.observacion = observacion;
    }
   
     @Id 

    
    @Column(name="idfac_cab", unique=true, nullable=false)
    public int getIdfacCab() {
        return this.idfacCab;
    }
    
    public void setIdfacCab(int idfacCab) {
        this.idfacCab = idfacCab;
    }

    
    @Column(name="fecha", nullable=false, length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="id_cliente", nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="subtotal", nullable=false, length=45)
    public String getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="desceunto", nullable=false, length=45)
    public String getDesceunto() {
        return this.desceunto;
    }
    
    public void setDesceunto(String desceunto) {
        this.desceunto = desceunto;
    }

    
    @Column(name="iva", nullable=false, length=45)
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }

    
    @Column(name="total", nullable=false, length=45)
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }

    
    @Column(name="observacion", nullable=false, length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


