package Datos;
// Generated 02/07/2022 0:41:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FacDet generated by hbm2java
 */
@Entity
@Table(name="fac_det"
    ,catalog="sgjn"
)
public class FacDet  implements java.io.Serializable {


     private int idfacDet;
     private byte cantidad;
     private byte total;

    public FacDet() {
    }

    public FacDet(int idfacDet, byte cantidad, byte total) {
       this.idfacDet = idfacDet;
       this.cantidad = cantidad;
       this.total = total;
    }
   
     @Id 

    
    @Column(name="idfac_det", unique=true, nullable=false)
    public int getIdfacDet() {
        return this.idfacDet;
    }
    
    public void setIdfacDet(int idfacDet) {
        this.idfacDet = idfacDet;
    }

    
    @Column(name="cantidad", nullable=false, precision=2, scale=0)
    public byte getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(byte cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="total", nullable=false, precision=2, scale=0)
    public byte getTotal() {
        return this.total;
    }
    
    public void setTotal(byte total) {
        this.total = total;
    }




}


