package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnRol generated by hbm2java
 */
@Entity
@Table(name="sgjn_rol"
    ,catalog="sgjn"
)
public class SgjnRol  implements java.io.Serializable {


     private int jnrolCodigo;
     private String jnrolNombre;
     private String jnrolEstado;
     private String jnrolUsuarioInsert;
     private Date jnrolFechaInsert;
     private String jnrolUsuarioUpdate;
     private Date jnrolFechaUpdate;

    public SgjnRol() {
    }

    public SgjnRol(int jnrolCodigo, String jnrolNombre, String jnrolEstado, String jnrolUsuarioInsert, Date jnrolFechaInsert, String jnrolUsuarioUpdate, Date jnrolFechaUpdate) {
       this.jnrolCodigo = jnrolCodigo;
       this.jnrolNombre = jnrolNombre;
       this.jnrolEstado = jnrolEstado;
       this.jnrolUsuarioInsert = jnrolUsuarioInsert;
       this.jnrolFechaInsert = jnrolFechaInsert;
       this.jnrolUsuarioUpdate = jnrolUsuarioUpdate;
       this.jnrolFechaUpdate = jnrolFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnrol_codigo", unique=true, nullable=false)
    public int getJnrolCodigo() {
        return this.jnrolCodigo;
    }
    
    public void setJnrolCodigo(int jnrolCodigo) {
        this.jnrolCodigo = jnrolCodigo;
    }

    
    @Column(name="jnrol_nombre", nullable=false, length=25)
    public String getJnrolNombre() {
        return this.jnrolNombre;
    }
    
    public void setJnrolNombre(String jnrolNombre) {
        this.jnrolNombre = jnrolNombre;
    }

    
    @Column(name="jnrol_estado", nullable=false, length=1)
    public String getJnrolEstado() {
        return this.jnrolEstado;
    }
    
    public void setJnrolEstado(String jnrolEstado) {
        this.jnrolEstado = jnrolEstado;
    }

    
    @Column(name="jnrol_usuario_insert", nullable=false, length=50)
    public String getJnrolUsuarioInsert() {
        return this.jnrolUsuarioInsert;
    }
    
    public void setJnrolUsuarioInsert(String jnrolUsuarioInsert) {
        this.jnrolUsuarioInsert = jnrolUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnrol_fecha_insert", nullable=false, length=19)
    public Date getJnrolFechaInsert() {
        return this.jnrolFechaInsert;
    }
    
    public void setJnrolFechaInsert(Date jnrolFechaInsert) {
        this.jnrolFechaInsert = jnrolFechaInsert;
    }

    
    @Column(name="jnrol_usuario_update", nullable=false, length=50)
    public String getJnrolUsuarioUpdate() {
        return this.jnrolUsuarioUpdate;
    }
    
    public void setJnrolUsuarioUpdate(String jnrolUsuarioUpdate) {
        this.jnrolUsuarioUpdate = jnrolUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnrol_fecha_update", nullable=false, length=19)
    public Date getJnrolFechaUpdate() {
        return this.jnrolFechaUpdate;
    }
    
    public void setJnrolFechaUpdate(Date jnrolFechaUpdate) {
        this.jnrolFechaUpdate = jnrolFechaUpdate;
    }




}


