package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SgjnCiudad generated by hbm2java
 */
@Entity
@Table(name="sgjn_ciudad"
    ,catalog="sgjn"
)
public class SgjnCiudad  implements java.io.Serializable {


     private int jnprovCodigo;
     private int jnciuCodigo;
     private String jnciuNombre;
     private String jnciuEstado;

    public SgjnCiudad() {
    }

    public SgjnCiudad(int jnprovCodigo, int jnciuCodigo, String jnciuNombre, String jnciuEstado) {
       this.jnprovCodigo = jnprovCodigo;
       this.jnciuCodigo = jnciuCodigo;
       this.jnciuNombre = jnciuNombre;
       this.jnciuEstado = jnciuEstado;
    }
   
     @Id 

    
    @Column(name="jnprov_codigo", unique=true, nullable=false)
    public int getJnprovCodigo() {
        return this.jnprovCodigo;
    }
    
    public void setJnprovCodigo(int jnprovCodigo) {
        this.jnprovCodigo = jnprovCodigo;
    }

    
    @Column(name="jnciu_codigo", nullable=false)
    public int getJnciuCodigo() {
        return this.jnciuCodigo;
    }
    
    public void setJnciuCodigo(int jnciuCodigo) {
        this.jnciuCodigo = jnciuCodigo;
    }

    
    @Column(name="jnciu_nombre", nullable=false, length=25)
    public String getJnciuNombre() {
        return this.jnciuNombre;
    }
    
    public void setJnciuNombre(String jnciuNombre) {
        this.jnciuNombre = jnciuNombre;
    }

    
    @Column(name="jnciu_estado", nullable=false, length=1)
    public String getJnciuEstado() {
        return this.jnciuEstado;
    }
    
    public void setJnciuEstado(String jnciuEstado) {
        this.jnciuEstado = jnciuEstado;
    }




}


