package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SgjnProvincia generated by hbm2java
 */
@Entity
@Table(name="sgjn_provincia"
    ,catalog="sgjn"
)
public class SgjnProvincia  implements java.io.Serializable {


     private int jnprovCodigo;
     private int jnpaisCodigo;
     private String jnprovNombre;
     private String jnprovEstado;

    public SgjnProvincia() {
    }

	
    public SgjnProvincia(int jnprovCodigo, int jnpaisCodigo, String jnprovEstado) {
        this.jnprovCodigo = jnprovCodigo;
        this.jnpaisCodigo = jnpaisCodigo;
        this.jnprovEstado = jnprovEstado;
    }
    public SgjnProvincia(int jnprovCodigo, int jnpaisCodigo, String jnprovNombre, String jnprovEstado) {
       this.jnprovCodigo = jnprovCodigo;
       this.jnpaisCodigo = jnpaisCodigo;
       this.jnprovNombre = jnprovNombre;
       this.jnprovEstado = jnprovEstado;
    }
   
     @Id 

    
    @Column(name="jnprov_codigo", unique=true, nullable=false)
    public int getJnprovCodigo() {
        return this.jnprovCodigo;
    }
    
    public void setJnprovCodigo(int jnprovCodigo) {
        this.jnprovCodigo = jnprovCodigo;
    }

    
    @Column(name="jnpais_codigo", nullable=false)
    public int getJnpaisCodigo() {
        return this.jnpaisCodigo;
    }
    
    public void setJnpaisCodigo(int jnpaisCodigo) {
        this.jnpaisCodigo = jnpaisCodigo;
    }

    
    @Column(name="jnprov_nombre", length=25)
    public String getJnprovNombre() {
        return this.jnprovNombre;
    }
    
    public void setJnprovNombre(String jnprovNombre) {
        this.jnprovNombre = jnprovNombre;
    }

    
    @Column(name="jnprov_estado", nullable=false, length=1)
    public String getJnprovEstado() {
        return this.jnprovEstado;
    }
    
    public void setJnprovEstado(String jnprovEstado) {
        this.jnprovEstado = jnprovEstado;
    }




}


