package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnFactura generated by hbm2java
 */
@Entity
@Table(name="sgjn_factura"
    ,catalog="sgjn"
)
public class SgjnFactura  implements java.io.Serializable {


     private int jnfacCodigo;
     private int jnperCodigo;
     private int jnempCodigo;
     private String jnfacNumero;
     private Date jnfacFechaEmision;
     private Date jnfacFechaVencimiento;
     private double jnvSubtotal;
     private double jnfacPorcentIva;
     private double jnfacDescuento;
     private double jnfacTotal;
     private String jnfacObservacion;
     private String jnfacUsuarioInsert;
     private Date jnfacFechaInsert;
     private String jnfacUsuarioUpdate;
     private Date jnfacFechaUpdate;

    public SgjnFactura() {
    }

    public SgjnFactura(int jnfacCodigo, int jnperCodigo, int jnempCodigo, String jnfacNumero, Date jnfacFechaEmision, Date jnfacFechaVencimiento, double jnvSubtotal, double jnfacPorcentIva, double jnfacDescuento, double jnfacTotal, String jnfacObservacion, String jnfacUsuarioInsert, Date jnfacFechaInsert, String jnfacUsuarioUpdate, Date jnfacFechaUpdate) {
       this.jnfacCodigo = jnfacCodigo;
       this.jnperCodigo = jnperCodigo;
       this.jnempCodigo = jnempCodigo;
       this.jnfacNumero = jnfacNumero;
       this.jnfacFechaEmision = jnfacFechaEmision;
       this.jnfacFechaVencimiento = jnfacFechaVencimiento;
       this.jnvSubtotal = jnvSubtotal;
       this.jnfacPorcentIva = jnfacPorcentIva;
       this.jnfacDescuento = jnfacDescuento;
       this.jnfacTotal = jnfacTotal;
       this.jnfacObservacion = jnfacObservacion;
       this.jnfacUsuarioInsert = jnfacUsuarioInsert;
       this.jnfacFechaInsert = jnfacFechaInsert;
       this.jnfacUsuarioUpdate = jnfacUsuarioUpdate;
       this.jnfacFechaUpdate = jnfacFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnfac_codigo", unique=true, nullable=false)
    public int getJnfacCodigo() {
        return this.jnfacCodigo;
    }
    
    public void setJnfacCodigo(int jnfacCodigo) {
        this.jnfacCodigo = jnfacCodigo;
    }

    
    @Column(name="jnper_codigo", nullable=false)
    public int getJnperCodigo() {
        return this.jnperCodigo;
    }
    
    public void setJnperCodigo(int jnperCodigo) {
        this.jnperCodigo = jnperCodigo;
    }

    
    @Column(name="jnemp_codigo", nullable=false)
    public int getJnempCodigo() {
        return this.jnempCodigo;
    }
    
    public void setJnempCodigo(int jnempCodigo) {
        this.jnempCodigo = jnempCodigo;
    }

    
    @Column(name="jnfac_numero", nullable=false, length=20)
    public String getJnfacNumero() {
        return this.jnfacNumero;
    }
    
    public void setJnfacNumero(String jnfacNumero) {
        this.jnfacNumero = jnfacNumero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jnfac_fecha_emision", nullable=false, length=10)
    public Date getJnfacFechaEmision() {
        return this.jnfacFechaEmision;
    }
    
    public void setJnfacFechaEmision(Date jnfacFechaEmision) {
        this.jnfacFechaEmision = jnfacFechaEmision;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jnfac_fecha_vencimiento", nullable=false, length=10)
    public Date getJnfacFechaVencimiento() {
        return this.jnfacFechaVencimiento;
    }
    
    public void setJnfacFechaVencimiento(Date jnfacFechaVencimiento) {
        this.jnfacFechaVencimiento = jnfacFechaVencimiento;
    }

    
    @Column(name="jnv_subtotal", nullable=false, precision=10)
    public double getJnvSubtotal() {
        return this.jnvSubtotal;
    }
    
    public void setJnvSubtotal(double jnvSubtotal) {
        this.jnvSubtotal = jnvSubtotal;
    }

    
    @Column(name="jnfac_porcent_iva", nullable=false, precision=5)
    public double getJnfacPorcentIva() {
        return this.jnfacPorcentIva;
    }
    
    public void setJnfacPorcentIva(double jnfacPorcentIva) {
        this.jnfacPorcentIva = jnfacPorcentIva;
    }

    
    @Column(name="jnfac_descuento", nullable=false, precision=5)
    public double getJnfacDescuento() {
        return this.jnfacDescuento;
    }
    
    public void setJnfacDescuento(double jnfacDescuento) {
        this.jnfacDescuento = jnfacDescuento;
    }

    
    @Column(name="jnfac_total", nullable=false, precision=10, scale=3)
    public double getJnfacTotal() {
        return this.jnfacTotal;
    }
    
    public void setJnfacTotal(double jnfacTotal) {
        this.jnfacTotal = jnfacTotal;
    }

    
    @Column(name="jnfac_observacion", nullable=false, length=30)
    public String getJnfacObservacion() {
        return this.jnfacObservacion;
    }
    
    public void setJnfacObservacion(String jnfacObservacion) {
        this.jnfacObservacion = jnfacObservacion;
    }

    
    @Column(name="jnfac_usuario_insert", nullable=false, length=50)
    public String getJnfacUsuarioInsert() {
        return this.jnfacUsuarioInsert;
    }
    
    public void setJnfacUsuarioInsert(String jnfacUsuarioInsert) {
        this.jnfacUsuarioInsert = jnfacUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnfac_fecha_insert", nullable=false, length=19)
    public Date getJnfacFechaInsert() {
        return this.jnfacFechaInsert;
    }
    
    public void setJnfacFechaInsert(Date jnfacFechaInsert) {
        this.jnfacFechaInsert = jnfacFechaInsert;
    }

    
    @Column(name="jnfac_usuario_update", nullable=false, length=50)
    public String getJnfacUsuarioUpdate() {
        return this.jnfacUsuarioUpdate;
    }
    
    public void setJnfacUsuarioUpdate(String jnfacUsuarioUpdate) {
        this.jnfacUsuarioUpdate = jnfacUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnfac_fecha_update", nullable=false, length=19)
    public Date getJnfacFechaUpdate() {
        return this.jnfacFechaUpdate;
    }
    
    public void setJnfacFechaUpdate(Date jnfacFechaUpdate) {
        this.jnfacFechaUpdate = jnfacFechaUpdate;
    }




}


