package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnProformaDetalle generated by hbm2java
 */
@Entity
@Table(name="sgjn_proforma_detalle"
    ,catalog="sgjn"
)
public class SgjnProformaDetalle  implements java.io.Serializable {


     private int jnpdetCodigo;
     private int jnprofCodigo;
     private int jnprodCodigo;
     private double jnpdetValorUnitario;
     private double jnpdetValorDescuento;
     private double jnpdetTotalUnitario;
     private String jnpdetUsuarioInsert;
     private Date jnpdetFechaInsert;
     private String jnpdetUsuarioUpdate;
     private Date jnpdetFechaUpdate;

    public SgjnProformaDetalle() {
    }

    public SgjnProformaDetalle(int jnpdetCodigo, int jnprofCodigo, int jnprodCodigo, double jnpdetValorUnitario, double jnpdetValorDescuento, double jnpdetTotalUnitario, String jnpdetUsuarioInsert, Date jnpdetFechaInsert, String jnpdetUsuarioUpdate, Date jnpdetFechaUpdate) {
       this.jnpdetCodigo = jnpdetCodigo;
       this.jnprofCodigo = jnprofCodigo;
       this.jnprodCodigo = jnprodCodigo;
       this.jnpdetValorUnitario = jnpdetValorUnitario;
       this.jnpdetValorDescuento = jnpdetValorDescuento;
       this.jnpdetTotalUnitario = jnpdetTotalUnitario;
       this.jnpdetUsuarioInsert = jnpdetUsuarioInsert;
       this.jnpdetFechaInsert = jnpdetFechaInsert;
       this.jnpdetUsuarioUpdate = jnpdetUsuarioUpdate;
       this.jnpdetFechaUpdate = jnpdetFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnpdet_codigo", unique=true, nullable=false)
    public int getJnpdetCodigo() {
        return this.jnpdetCodigo;
    }
    
    public void setJnpdetCodigo(int jnpdetCodigo) {
        this.jnpdetCodigo = jnpdetCodigo;
    }

    
    @Column(name="jnprof_codigo", nullable=false)
    public int getJnprofCodigo() {
        return this.jnprofCodigo;
    }
    
    public void setJnprofCodigo(int jnprofCodigo) {
        this.jnprofCodigo = jnprofCodigo;
    }

    
    @Column(name="jnprod_codigo", nullable=false)
    public int getJnprodCodigo() {
        return this.jnprodCodigo;
    }
    
    public void setJnprodCodigo(int jnprodCodigo) {
        this.jnprodCodigo = jnprodCodigo;
    }

    
    @Column(name="jnpdet_valor_unitario", nullable=false, precision=10, scale=3)
    public double getJnpdetValorUnitario() {
        return this.jnpdetValorUnitario;
    }
    
    public void setJnpdetValorUnitario(double jnpdetValorUnitario) {
        this.jnpdetValorUnitario = jnpdetValorUnitario;
    }

    
    @Column(name="jnpdet_valor_descuento", nullable=false, precision=10, scale=3)
    public double getJnpdetValorDescuento() {
        return this.jnpdetValorDescuento;
    }
    
    public void setJnpdetValorDescuento(double jnpdetValorDescuento) {
        this.jnpdetValorDescuento = jnpdetValorDescuento;
    }

    
    @Column(name="jnpdet_total_unitario", nullable=false, precision=10, scale=3)
    public double getJnpdetTotalUnitario() {
        return this.jnpdetTotalUnitario;
    }
    
    public void setJnpdetTotalUnitario(double jnpdetTotalUnitario) {
        this.jnpdetTotalUnitario = jnpdetTotalUnitario;
    }

    
    @Column(name="jnpdet_usuario_insert", nullable=false, length=50)
    public String getJnpdetUsuarioInsert() {
        return this.jnpdetUsuarioInsert;
    }
    
    public void setJnpdetUsuarioInsert(String jnpdetUsuarioInsert) {
        this.jnpdetUsuarioInsert = jnpdetUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnpdet_fecha_insert", nullable=false, length=19)
    public Date getJnpdetFechaInsert() {
        return this.jnpdetFechaInsert;
    }
    
    public void setJnpdetFechaInsert(Date jnpdetFechaInsert) {
        this.jnpdetFechaInsert = jnpdetFechaInsert;
    }

    
    @Column(name="jnpdet_usuario_update", nullable=false, length=50)
    public String getJnpdetUsuarioUpdate() {
        return this.jnpdetUsuarioUpdate;
    }
    
    public void setJnpdetUsuarioUpdate(String jnpdetUsuarioUpdate) {
        this.jnpdetUsuarioUpdate = jnpdetUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnpdet_fecha_update", nullable=false, length=19)
    public Date getJnpdetFechaUpdate() {
        return this.jnpdetFechaUpdate;
    }
    
    public void setJnpdetFechaUpdate(Date jnpdetFechaUpdate) {
        this.jnpdetFechaUpdate = jnpdetFechaUpdate;
    }




}


