package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnTipoFormaPago generated by hbm2java
 */
@Entity
@Table(name="sgjn_tipo_forma_pago"
    ,catalog="sgjn"
)
public class SgjnTipoFormaPago  implements java.io.Serializable {


     private int jntfpCodigo;
     private int jnpcdCodigo;
     private int jnaCodigo;
     private String jntfpNombre;
     private String jntfpDescripcion;
     private boolean jntfpEstadoTipo;
     private String jntfpUsuarioInsert;
     private Date jntfpFechaInsert;
     private String jntfpUsuarioUpdate;
     private Date jntfpFechaUpdate;

    public SgjnTipoFormaPago() {
    }

    public SgjnTipoFormaPago(int jntfpCodigo, int jnpcdCodigo, int jnaCodigo, String jntfpNombre, String jntfpDescripcion, boolean jntfpEstadoTipo, String jntfpUsuarioInsert, Date jntfpFechaInsert, String jntfpUsuarioUpdate, Date jntfpFechaUpdate) {
       this.jntfpCodigo = jntfpCodigo;
       this.jnpcdCodigo = jnpcdCodigo;
       this.jnaCodigo = jnaCodigo;
       this.jntfpNombre = jntfpNombre;
       this.jntfpDescripcion = jntfpDescripcion;
       this.jntfpEstadoTipo = jntfpEstadoTipo;
       this.jntfpUsuarioInsert = jntfpUsuarioInsert;
       this.jntfpFechaInsert = jntfpFechaInsert;
       this.jntfpUsuarioUpdate = jntfpUsuarioUpdate;
       this.jntfpFechaUpdate = jntfpFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jntfp_codigo", unique=true, nullable=false)
    public int getJntfpCodigo() {
        return this.jntfpCodigo;
    }
    
    public void setJntfpCodigo(int jntfpCodigo) {
        this.jntfpCodigo = jntfpCodigo;
    }

    
    @Column(name="jnpcd_codigo", nullable=false)
    public int getJnpcdCodigo() {
        return this.jnpcdCodigo;
    }
    
    public void setJnpcdCodigo(int jnpcdCodigo) {
        this.jnpcdCodigo = jnpcdCodigo;
    }

    
    @Column(name="jna_codigo", nullable=false)
    public int getJnaCodigo() {
        return this.jnaCodigo;
    }
    
    public void setJnaCodigo(int jnaCodigo) {
        this.jnaCodigo = jnaCodigo;
    }

    
    @Column(name="jntfp_nombre", nullable=false, length=50)
    public String getJntfpNombre() {
        return this.jntfpNombre;
    }
    
    public void setJntfpNombre(String jntfpNombre) {
        this.jntfpNombre = jntfpNombre;
    }

    
    @Column(name="jntfp_descripcion", nullable=false, length=50)
    public String getJntfpDescripcion() {
        return this.jntfpDescripcion;
    }
    
    public void setJntfpDescripcion(String jntfpDescripcion) {
        this.jntfpDescripcion = jntfpDescripcion;
    }

    
    @Column(name="jntfp_estado_tipo", nullable=false)
    public boolean isJntfpEstadoTipo() {
        return this.jntfpEstadoTipo;
    }
    
    public void setJntfpEstadoTipo(boolean jntfpEstadoTipo) {
        this.jntfpEstadoTipo = jntfpEstadoTipo;
    }

    
    @Column(name="jntfp_usuario_insert", nullable=false, length=50)
    public String getJntfpUsuarioInsert() {
        return this.jntfpUsuarioInsert;
    }
    
    public void setJntfpUsuarioInsert(String jntfpUsuarioInsert) {
        this.jntfpUsuarioInsert = jntfpUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jntfp_fecha_insert", nullable=false, length=19)
    public Date getJntfpFechaInsert() {
        return this.jntfpFechaInsert;
    }
    
    public void setJntfpFechaInsert(Date jntfpFechaInsert) {
        this.jntfpFechaInsert = jntfpFechaInsert;
    }

    
    @Column(name="jntfp_usuario_update", nullable=false, length=50)
    public String getJntfpUsuarioUpdate() {
        return this.jntfpUsuarioUpdate;
    }
    
    public void setJntfpUsuarioUpdate(String jntfpUsuarioUpdate) {
        this.jntfpUsuarioUpdate = jntfpUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jntfp_fecha_update", nullable=false, length=19)
    public Date getJntfpFechaUpdate() {
        return this.jntfpFechaUpdate;
    }
    
    public void setJntfpFechaUpdate(Date jntfpFechaUpdate) {
        this.jntfpFechaUpdate = jntfpFechaUpdate;
    }




}


