package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnProducto generated by hbm2java
 */
@Entity
@Table(name="sgjn_producto"
    ,catalog="sgjn"
)
public class SgjnProducto  implements java.io.Serializable {


     private int jnprodCodigo;
     private int jncatCodigo;
     private int jnumCodigo;
     private int jnmrCodigo;
     private int jnmodCodigo;
     private int jnbodCodigo;
     private String jnprodNombre;
     private String jnprodEstado;
     private double jnprodPrecioCosto;
     private double jnprodPrecioVenta;
     private double jnprodPrecioMayoreo;
     private double jnprodStock;
     private double jnprodStockMinimo;
     private String jnprodUsuarioInsert;
     private Date jnprodFechaInsert;
     private String jnprodUsuarioUpdate;
     private Date jnprodFechaUpdate;

    public SgjnProducto() {
    }

    public SgjnProducto(int jnprodCodigo, int jncatCodigo, int jnumCodigo, int jnmrCodigo, int jnmodCodigo, int jnbodCodigo, String jnprodNombre, String jnprodEstado, double jnprodPrecioCosto, double jnprodPrecioVenta, double jnprodPrecioMayoreo, double jnprodStock, double jnprodStockMinimo, String jnprodUsuarioInsert, Date jnprodFechaInsert, String jnprodUsuarioUpdate, Date jnprodFechaUpdate) {
       this.jnprodCodigo = jnprodCodigo;
       this.jncatCodigo = jncatCodigo;
       this.jnumCodigo = jnumCodigo;
       this.jnmrCodigo = jnmrCodigo;
       this.jnmodCodigo = jnmodCodigo;
       this.jnbodCodigo = jnbodCodigo;
       this.jnprodNombre = jnprodNombre;
       this.jnprodEstado = jnprodEstado;
       this.jnprodPrecioCosto = jnprodPrecioCosto;
       this.jnprodPrecioVenta = jnprodPrecioVenta;
       this.jnprodPrecioMayoreo = jnprodPrecioMayoreo;
       this.jnprodStock = jnprodStock;
       this.jnprodStockMinimo = jnprodStockMinimo;
       this.jnprodUsuarioInsert = jnprodUsuarioInsert;
       this.jnprodFechaInsert = jnprodFechaInsert;
       this.jnprodUsuarioUpdate = jnprodUsuarioUpdate;
       this.jnprodFechaUpdate = jnprodFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnprod_codigo", unique=true, nullable=false)
    public int getJnprodCodigo() {
        return this.jnprodCodigo;
    }
    
    public void setJnprodCodigo(int jnprodCodigo) {
        this.jnprodCodigo = jnprodCodigo;
    }

    
    @Column(name="jncat_codigo", nullable=false)
    public int getJncatCodigo() {
        return this.jncatCodigo;
    }
    
    public void setJncatCodigo(int jncatCodigo) {
        this.jncatCodigo = jncatCodigo;
    }

    
    @Column(name="jnum_codigo", nullable=false)
    public int getJnumCodigo() {
        return this.jnumCodigo;
    }
    
    public void setJnumCodigo(int jnumCodigo) {
        this.jnumCodigo = jnumCodigo;
    }

    
    @Column(name="jnmr_codigo", nullable=false)
    public int getJnmrCodigo() {
        return this.jnmrCodigo;
    }
    
    public void setJnmrCodigo(int jnmrCodigo) {
        this.jnmrCodigo = jnmrCodigo;
    }

    
    @Column(name="jnmod_codigo", nullable=false)
    public int getJnmodCodigo() {
        return this.jnmodCodigo;
    }
    
    public void setJnmodCodigo(int jnmodCodigo) {
        this.jnmodCodigo = jnmodCodigo;
    }

    
    @Column(name="jnbod_codigo", nullable=false)
    public int getJnbodCodigo() {
        return this.jnbodCodigo;
    }
    
    public void setJnbodCodigo(int jnbodCodigo) {
        this.jnbodCodigo = jnbodCodigo;
    }

    
    @Column(name="jnprod_nombre", nullable=false, length=25)
    public String getJnprodNombre() {
        return this.jnprodNombre;
    }
    
    public void setJnprodNombre(String jnprodNombre) {
        this.jnprodNombre = jnprodNombre;
    }

    
    @Column(name="jnprod_estado", nullable=false, length=1)
    public String getJnprodEstado() {
        return this.jnprodEstado;
    }
    
    public void setJnprodEstado(String jnprodEstado) {
        this.jnprodEstado = jnprodEstado;
    }

    
    @Column(name="jnprod_precio_costo", nullable=false, precision=10)
    public double getJnprodPrecioCosto() {
        return this.jnprodPrecioCosto;
    }
    
    public void setJnprodPrecioCosto(double jnprodPrecioCosto) {
        this.jnprodPrecioCosto = jnprodPrecioCosto;
    }

    
    @Column(name="jnprod_precio_venta", nullable=false, precision=10)
    public double getJnprodPrecioVenta() {
        return this.jnprodPrecioVenta;
    }
    
    public void setJnprodPrecioVenta(double jnprodPrecioVenta) {
        this.jnprodPrecioVenta = jnprodPrecioVenta;
    }

    
    @Column(name="jnprod_precio_mayoreo", nullable=false, precision=10)
    public double getJnprodPrecioMayoreo() {
        return this.jnprodPrecioMayoreo;
    }
    
    public void setJnprodPrecioMayoreo(double jnprodPrecioMayoreo) {
        this.jnprodPrecioMayoreo = jnprodPrecioMayoreo;
    }

    
    @Column(name="jnprod_stock", nullable=false, precision=10)
    public double getJnprodStock() {
        return this.jnprodStock;
    }
    
    public void setJnprodStock(double jnprodStock) {
        this.jnprodStock = jnprodStock;
    }

    
    @Column(name="jnprod_stock_minimo", nullable=false, precision=10)
    public double getJnprodStockMinimo() {
        return this.jnprodStockMinimo;
    }
    
    public void setJnprodStockMinimo(double jnprodStockMinimo) {
        this.jnprodStockMinimo = jnprodStockMinimo;
    }

    
    @Column(name="jnprod_usuario_insert", nullable=false, length=50)
    public String getJnprodUsuarioInsert() {
        return this.jnprodUsuarioInsert;
    }
    
    public void setJnprodUsuarioInsert(String jnprodUsuarioInsert) {
        this.jnprodUsuarioInsert = jnprodUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnprod_fecha_insert", nullable=false, length=19)
    public Date getJnprodFechaInsert() {
        return this.jnprodFechaInsert;
    }
    
    public void setJnprodFechaInsert(Date jnprodFechaInsert) {
        this.jnprodFechaInsert = jnprodFechaInsert;
    }

    
    @Column(name="jnprod_usuario_update", nullable=false, length=50)
    public String getJnprodUsuarioUpdate() {
        return this.jnprodUsuarioUpdate;
    }
    
    public void setJnprodUsuarioUpdate(String jnprodUsuarioUpdate) {
        this.jnprodUsuarioUpdate = jnprodUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnprod_fecha_update", nullable=false, length=19)
    public Date getJnprodFechaUpdate() {
        return this.jnprodFechaUpdate;
    }
    
    public void setJnprodFechaUpdate(Date jnprodFechaUpdate) {
        this.jnprodFechaUpdate = jnprodFechaUpdate;
    }




}


