package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnUnidadMedida generated by hbm2java
 */
@Entity
@Table(name="sgjn_unidad_medida"
    ,catalog="sgjn"
)
public class SgjnUnidadMedida  implements java.io.Serializable {


     private int jnumCodigo;
     private String jnumNombre;
     private boolean jnumEstado;
     private String jnumUsuarioInsert;
     private Date jnumFechaInsert;
     private String jnumUsuarioUpdate;
     private Date jnumFechaUpdate;

    public SgjnUnidadMedida() {
    }

    public SgjnUnidadMedida(int jnumCodigo, String jnumNombre, boolean jnumEstado, String jnumUsuarioInsert, Date jnumFechaInsert, String jnumUsuarioUpdate, Date jnumFechaUpdate) {
       this.jnumCodigo = jnumCodigo;
       this.jnumNombre = jnumNombre;
       this.jnumEstado = jnumEstado;
       this.jnumUsuarioInsert = jnumUsuarioInsert;
       this.jnumFechaInsert = jnumFechaInsert;
       this.jnumUsuarioUpdate = jnumUsuarioUpdate;
       this.jnumFechaUpdate = jnumFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnum_codigo", unique=true, nullable=false)
    public int getJnumCodigo() {
        return this.jnumCodigo;
    }
    
    public void setJnumCodigo(int jnumCodigo) {
        this.jnumCodigo = jnumCodigo;
    }

    
    @Column(name="jnum_nombre", nullable=false, length=25)
    public String getJnumNombre() {
        return this.jnumNombre;
    }
    
    public void setJnumNombre(String jnumNombre) {
        this.jnumNombre = jnumNombre;
    }

    
    @Column(name="jnum_estado", nullable=false)
    public boolean isJnumEstado() {
        return this.jnumEstado;
    }
    
    public void setJnumEstado(boolean jnumEstado) {
        this.jnumEstado = jnumEstado;
    }

    
    @Column(name="jnum_usuario_insert", nullable=false, length=50)
    public String getJnumUsuarioInsert() {
        return this.jnumUsuarioInsert;
    }
    
    public void setJnumUsuarioInsert(String jnumUsuarioInsert) {
        this.jnumUsuarioInsert = jnumUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnum_fecha_insert", nullable=false, length=19)
    public Date getJnumFechaInsert() {
        return this.jnumFechaInsert;
    }
    
    public void setJnumFechaInsert(Date jnumFechaInsert) {
        this.jnumFechaInsert = jnumFechaInsert;
    }

    
    @Column(name="jnum_usuario_update", nullable=false, length=50)
    public String getJnumUsuarioUpdate() {
        return this.jnumUsuarioUpdate;
    }
    
    public void setJnumUsuarioUpdate(String jnumUsuarioUpdate) {
        this.jnumUsuarioUpdate = jnumUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnum_fecha_update", nullable=false, length=19)
    public Date getJnumFechaUpdate() {
        return this.jnumFechaUpdate;
    }
    
    public void setJnumFechaUpdate(Date jnumFechaUpdate) {
        this.jnumFechaUpdate = jnumFechaUpdate;
    }




}


