package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnCompra generated by hbm2java
 */
@Entity
@Table(name="sgjn_compra"
    ,catalog="sgjn"
)
public class SgjnCompra  implements java.io.Serializable {


     private int jncomCodigo;
     private int jnperCodigo;
     private int jnempCodigo;
     private String jncomNumero;
     private Date jncomFechaEmision;
     private Date jncomFechaVencimiento;
     private double jncomSubtotal;
     private double jncomPorcentIva;
     private double jncomDescuento;
     private double jncomTotal;
     private String jncomObservacion;
     private String jncomUsuarioInsert;
     private Date jncomFechaInsert;
     private String jncomUsuarioUpdate;
     private Date jncomFechaUpdate;

    public SgjnCompra() {
    }

    public SgjnCompra(int jncomCodigo, int jnperCodigo, int jnempCodigo, String jncomNumero, Date jncomFechaEmision, Date jncomFechaVencimiento, double jncomSubtotal, double jncomPorcentIva, double jncomDescuento, double jncomTotal, String jncomObservacion, String jncomUsuarioInsert, Date jncomFechaInsert, String jncomUsuarioUpdate, Date jncomFechaUpdate) {
       this.jncomCodigo = jncomCodigo;
       this.jnperCodigo = jnperCodigo;
       this.jnempCodigo = jnempCodigo;
       this.jncomNumero = jncomNumero;
       this.jncomFechaEmision = jncomFechaEmision;
       this.jncomFechaVencimiento = jncomFechaVencimiento;
       this.jncomSubtotal = jncomSubtotal;
       this.jncomPorcentIva = jncomPorcentIva;
       this.jncomDescuento = jncomDescuento;
       this.jncomTotal = jncomTotal;
       this.jncomObservacion = jncomObservacion;
       this.jncomUsuarioInsert = jncomUsuarioInsert;
       this.jncomFechaInsert = jncomFechaInsert;
       this.jncomUsuarioUpdate = jncomUsuarioUpdate;
       this.jncomFechaUpdate = jncomFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jncom_codigo", unique=true, nullable=false)
    public int getJncomCodigo() {
        return this.jncomCodigo;
    }
    
    public void setJncomCodigo(int jncomCodigo) {
        this.jncomCodigo = jncomCodigo;
    }

    
    @Column(name="jnper_codigo", nullable=false)
    public int getJnperCodigo() {
        return this.jnperCodigo;
    }
    
    public void setJnperCodigo(int jnperCodigo) {
        this.jnperCodigo = jnperCodigo;
    }

    
    @Column(name="jnemp_codigo", nullable=false)
    public int getJnempCodigo() {
        return this.jnempCodigo;
    }
    
    public void setJnempCodigo(int jnempCodigo) {
        this.jnempCodigo = jnempCodigo;
    }

    
    @Column(name="jncom_numero", nullable=false, length=20)
    public String getJncomNumero() {
        return this.jncomNumero;
    }
    
    public void setJncomNumero(String jncomNumero) {
        this.jncomNumero = jncomNumero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jncom_fecha_emision", nullable=false, length=10)
    public Date getJncomFechaEmision() {
        return this.jncomFechaEmision;
    }
    
    public void setJncomFechaEmision(Date jncomFechaEmision) {
        this.jncomFechaEmision = jncomFechaEmision;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jncom_fecha_vencimiento", nullable=false, length=10)
    public Date getJncomFechaVencimiento() {
        return this.jncomFechaVencimiento;
    }
    
    public void setJncomFechaVencimiento(Date jncomFechaVencimiento) {
        this.jncomFechaVencimiento = jncomFechaVencimiento;
    }

    
    @Column(name="jncom_subtotal", nullable=false, precision=10)
    public double getJncomSubtotal() {
        return this.jncomSubtotal;
    }
    
    public void setJncomSubtotal(double jncomSubtotal) {
        this.jncomSubtotal = jncomSubtotal;
    }

    
    @Column(name="jncom_porcent_iva", nullable=false, precision=5)
    public double getJncomPorcentIva() {
        return this.jncomPorcentIva;
    }
    
    public void setJncomPorcentIva(double jncomPorcentIva) {
        this.jncomPorcentIva = jncomPorcentIva;
    }

    
    @Column(name="jncom_descuento", nullable=false, precision=5)
    public double getJncomDescuento() {
        return this.jncomDescuento;
    }
    
    public void setJncomDescuento(double jncomDescuento) {
        this.jncomDescuento = jncomDescuento;
    }

    
    @Column(name="jncom_total", nullable=false, precision=10, scale=3)
    public double getJncomTotal() {
        return this.jncomTotal;
    }
    
    public void setJncomTotal(double jncomTotal) {
        this.jncomTotal = jncomTotal;
    }

    
    @Column(name="jncom_observacion", nullable=false, length=30)
    public String getJncomObservacion() {
        return this.jncomObservacion;
    }
    
    public void setJncomObservacion(String jncomObservacion) {
        this.jncomObservacion = jncomObservacion;
    }

    
    @Column(name="jncom_usuario_insert", nullable=false, length=50)
    public String getJncomUsuarioInsert() {
        return this.jncomUsuarioInsert;
    }
    
    public void setJncomUsuarioInsert(String jncomUsuarioInsert) {
        this.jncomUsuarioInsert = jncomUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jncom_fecha_insert", nullable=false, length=19)
    public Date getJncomFechaInsert() {
        return this.jncomFechaInsert;
    }
    
    public void setJncomFechaInsert(Date jncomFechaInsert) {
        this.jncomFechaInsert = jncomFechaInsert;
    }

    
    @Column(name="jncom_usuario_update", nullable=false, length=50)
    public String getJncomUsuarioUpdate() {
        return this.jncomUsuarioUpdate;
    }
    
    public void setJncomUsuarioUpdate(String jncomUsuarioUpdate) {
        this.jncomUsuarioUpdate = jncomUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jncom_fecha_update", nullable=false, length=19)
    public Date getJncomFechaUpdate() {
        return this.jncomFechaUpdate;
    }
    
    public void setJncomFechaUpdate(Date jncomFechaUpdate) {
        this.jncomFechaUpdate = jncomFechaUpdate;
    }




}


