package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnCategoria generated by hbm2java
 */
@Entity
@Table(name="sgjn_categoria"
    ,catalog="sgjn"
)
public class SgjnCategoria  implements java.io.Serializable {


     private int jncatCodigo;
     private String jncatNombre;
     private boolean jncatEstado;
     private String jncatUsuarioInsert;
     private Date jncatFechaInsert;
     private String jncatUsuarioUpdate;
     private Date jncatFechaUpdate;

    public SgjnCategoria() {
    }

    public SgjnCategoria(int jncatCodigo, String jncatNombre, boolean jncatEstado, String jncatUsuarioInsert, Date jncatFechaInsert, String jncatUsuarioUpdate, Date jncatFechaUpdate) {
       this.jncatCodigo = jncatCodigo;
       this.jncatNombre = jncatNombre;
       this.jncatEstado = jncatEstado;
       this.jncatUsuarioInsert = jncatUsuarioInsert;
       this.jncatFechaInsert = jncatFechaInsert;
       this.jncatUsuarioUpdate = jncatUsuarioUpdate;
       this.jncatFechaUpdate = jncatFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jncat_codigo", unique=true, nullable=false)
    public int getJncatCodigo() {
        return this.jncatCodigo;
    }
    
    public void setJncatCodigo(int jncatCodigo) {
        this.jncatCodigo = jncatCodigo;
    }

    
    @Column(name="jncat_nombre", nullable=false, length=25)
    public String getJncatNombre() {
        return this.jncatNombre;
    }
    
    public void setJncatNombre(String jncatNombre) {
        this.jncatNombre = jncatNombre;
    }

    
    @Column(name="jncat_estado", nullable=false)
    public boolean isJncatEstado() {
        return this.jncatEstado;
    }
    
    public void setJncatEstado(boolean jncatEstado) {
        this.jncatEstado = jncatEstado;
    }

    
    @Column(name="jncat_usuario_insert", nullable=false, length=50)
    public String getJncatUsuarioInsert() {
        return this.jncatUsuarioInsert;
    }
    
    public void setJncatUsuarioInsert(String jncatUsuarioInsert) {
        this.jncatUsuarioInsert = jncatUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jncat_fecha_insert", nullable=false, length=19)
    public Date getJncatFechaInsert() {
        return this.jncatFechaInsert;
    }
    
    public void setJncatFechaInsert(Date jncatFechaInsert) {
        this.jncatFechaInsert = jncatFechaInsert;
    }

    
    @Column(name="jncat_usuario_update", nullable=false, length=50)
    public String getJncatUsuarioUpdate() {
        return this.jncatUsuarioUpdate;
    }
    
    public void setJncatUsuarioUpdate(String jncatUsuarioUpdate) {
        this.jncatUsuarioUpdate = jncatUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jncat_fecha_update", nullable=false, length=19)
    public Date getJncatFechaUpdate() {
        return this.jncatFechaUpdate;
    }
    
    public void setJncatFechaUpdate(Date jncatFechaUpdate) {
        this.jncatFechaUpdate = jncatFechaUpdate;
    }




}


