package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnModelo generated by hbm2java
 */
@Entity
@Table(name="sgjn_modelo"
    ,catalog="sgjn"
)
public class SgjnModelo  implements java.io.Serializable {


     private int jnmodCodigo;
     private String jnmodNombre;
     private boolean jnmodEstado;
     private String jnmodUsuarioInsert;
     private Date jnmodFechaInsert;
     private String jnmodUsuarioUpdate;
     private Date jnmodFechaUpdate;

    public SgjnModelo() {
    }

    public SgjnModelo(int jnmodCodigo, String jnmodNombre, boolean jnmodEstado, String jnmodUsuarioInsert, Date jnmodFechaInsert, String jnmodUsuarioUpdate, Date jnmodFechaUpdate) {
       this.jnmodCodigo = jnmodCodigo;
       this.jnmodNombre = jnmodNombre;
       this.jnmodEstado = jnmodEstado;
       this.jnmodUsuarioInsert = jnmodUsuarioInsert;
       this.jnmodFechaInsert = jnmodFechaInsert;
       this.jnmodUsuarioUpdate = jnmodUsuarioUpdate;
       this.jnmodFechaUpdate = jnmodFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnmod_codigo", unique=true, nullable=false)
    public int getJnmodCodigo() {
        return this.jnmodCodigo;
    }
    
    public void setJnmodCodigo(int jnmodCodigo) {
        this.jnmodCodigo = jnmodCodigo;
    }

    
    @Column(name="jnmod_nombre", nullable=false, length=25)
    public String getJnmodNombre() {
        return this.jnmodNombre;
    }
    
    public void setJnmodNombre(String jnmodNombre) {
        this.jnmodNombre = jnmodNombre;
    }

    
    @Column(name="jnmod_estado", nullable=false)
    public boolean isJnmodEstado() {
        return this.jnmodEstado;
    }
    
    public void setJnmodEstado(boolean jnmodEstado) {
        this.jnmodEstado = jnmodEstado;
    }

    
    @Column(name="jnmod_usuario_insert", nullable=false, length=50)
    public String getJnmodUsuarioInsert() {
        return this.jnmodUsuarioInsert;
    }
    
    public void setJnmodUsuarioInsert(String jnmodUsuarioInsert) {
        this.jnmodUsuarioInsert = jnmodUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnmod_fecha_insert", nullable=false, length=19)
    public Date getJnmodFechaInsert() {
        return this.jnmodFechaInsert;
    }
    
    public void setJnmodFechaInsert(Date jnmodFechaInsert) {
        this.jnmodFechaInsert = jnmodFechaInsert;
    }

    
    @Column(name="jnmod_usuario_update", nullable=false, length=50)
    public String getJnmodUsuarioUpdate() {
        return this.jnmodUsuarioUpdate;
    }
    
    public void setJnmodUsuarioUpdate(String jnmodUsuarioUpdate) {
        this.jnmodUsuarioUpdate = jnmodUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnmod_fecha_update", nullable=false, length=19)
    public Date getJnmodFechaUpdate() {
        return this.jnmodFechaUpdate;
    }
    
    public void setJnmodFechaUpdate(Date jnmodFechaUpdate) {
        this.jnmodFechaUpdate = jnmodFechaUpdate;
    }




}


