package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnBodega generated by hbm2java
 */
@Entity
@Table(name="sgjn_bodega"
    ,catalog="sgjn"
)
public class SgjnBodega  implements java.io.Serializable {


     private int jnbodCodigo;
     private String jnbodNombre;
     private String jnbodDireccion;
     private String jnbodResponsable;
     private String jnbodTelefono;
     private String jnbodEstado;
     private String jnbodUsuarioInsert;
     private Date jnbodFechaInsert;
     private String jnbodUsuarioUpdate;
     private Date jnbodFechaUpdate;

    public SgjnBodega() {
    }

    public SgjnBodega(int jnbodCodigo, String jnbodNombre, String jnbodDireccion, String jnbodResponsable, String jnbodTelefono, String jnbodEstado, String jnbodUsuarioInsert, Date jnbodFechaInsert, String jnbodUsuarioUpdate, Date jnbodFechaUpdate) {
       this.jnbodCodigo = jnbodCodigo;
       this.jnbodNombre = jnbodNombre;
       this.jnbodDireccion = jnbodDireccion;
       this.jnbodResponsable = jnbodResponsable;
       this.jnbodTelefono = jnbodTelefono;
       this.jnbodEstado = jnbodEstado;
       this.jnbodUsuarioInsert = jnbodUsuarioInsert;
       this.jnbodFechaInsert = jnbodFechaInsert;
       this.jnbodUsuarioUpdate = jnbodUsuarioUpdate;
       this.jnbodFechaUpdate = jnbodFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnbod_codigo", unique=true, nullable=false)
    public int getJnbodCodigo() {
        return this.jnbodCodigo;
    }
    
    public void setJnbodCodigo(int jnbodCodigo) {
        this.jnbodCodigo = jnbodCodigo;
    }

    
    @Column(name="jnbod_nombre", nullable=false, length=50)
    public String getJnbodNombre() {
        return this.jnbodNombre;
    }
    
    public void setJnbodNombre(String jnbodNombre) {
        this.jnbodNombre = jnbodNombre;
    }

    
    @Column(name="jnbod_direccion", nullable=false, length=50)
    public String getJnbodDireccion() {
        return this.jnbodDireccion;
    }
    
    public void setJnbodDireccion(String jnbodDireccion) {
        this.jnbodDireccion = jnbodDireccion;
    }

    
    @Column(name="jnbod_responsable", nullable=false, length=50)
    public String getJnbodResponsable() {
        return this.jnbodResponsable;
    }
    
    public void setJnbodResponsable(String jnbodResponsable) {
        this.jnbodResponsable = jnbodResponsable;
    }

    
    @Column(name="jnbod_telefono", nullable=false, length=50)
    public String getJnbodTelefono() {
        return this.jnbodTelefono;
    }
    
    public void setJnbodTelefono(String jnbodTelefono) {
        this.jnbodTelefono = jnbodTelefono;
    }

    
    @Column(name="jnbod_estado", nullable=false, length=1)
    public String getJnbodEstado() {
        return this.jnbodEstado;
    }
    
    public void setJnbodEstado(String jnbodEstado) {
        this.jnbodEstado = jnbodEstado;
    }

    
    @Column(name="jnbod_usuario_insert", nullable=false, length=50)
    public String getJnbodUsuarioInsert() {
        return this.jnbodUsuarioInsert;
    }
    
    public void setJnbodUsuarioInsert(String jnbodUsuarioInsert) {
        this.jnbodUsuarioInsert = jnbodUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnbod_fecha_insert", nullable=false, length=19)
    public Date getJnbodFechaInsert() {
        return this.jnbodFechaInsert;
    }
    
    public void setJnbodFechaInsert(Date jnbodFechaInsert) {
        this.jnbodFechaInsert = jnbodFechaInsert;
    }

    
    @Column(name="jnbod_usuario_update", nullable=false, length=50)
    public String getJnbodUsuarioUpdate() {
        return this.jnbodUsuarioUpdate;
    }
    
    public void setJnbodUsuarioUpdate(String jnbodUsuarioUpdate) {
        this.jnbodUsuarioUpdate = jnbodUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnbod_fecha_update", nullable=false, length=19)
    public Date getJnbodFechaUpdate() {
        return this.jnbodFechaUpdate;
    }
    
    public void setJnbodFechaUpdate(Date jnbodFechaUpdate) {
        this.jnbodFechaUpdate = jnbodFechaUpdate;
    }




}


