package datos;
// Generated 06/08/2022 20:55:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgjnMarca generated by hbm2java
 */
@Entity
@Table(name="sgjn_marca"
    ,catalog="sgjn"
)
public class SgjnMarca  implements java.io.Serializable {


     private int jnmrCodigo;
     private String jnmrNombre;
     private boolean jnmrEstado;
     private String jnmrUsuarioInsert;
     private Date jnmrFechaInsert;
     private String jnmrUsuarioUpdate;
     private Date jnmrFechaUpdate;

    public SgjnMarca() {
    }

    public SgjnMarca(int jnmrCodigo, String jnmrNombre, boolean jnmrEstado, String jnmrUsuarioInsert, Date jnmrFechaInsert, String jnmrUsuarioUpdate, Date jnmrFechaUpdate) {
       this.jnmrCodigo = jnmrCodigo;
       this.jnmrNombre = jnmrNombre;
       this.jnmrEstado = jnmrEstado;
       this.jnmrUsuarioInsert = jnmrUsuarioInsert;
       this.jnmrFechaInsert = jnmrFechaInsert;
       this.jnmrUsuarioUpdate = jnmrUsuarioUpdate;
       this.jnmrFechaUpdate = jnmrFechaUpdate;
    }
   
     @Id 

    
    @Column(name="jnmr_codigo", unique=true, nullable=false)
    public int getJnmrCodigo() {
        return this.jnmrCodigo;
    }
    
    public void setJnmrCodigo(int jnmrCodigo) {
        this.jnmrCodigo = jnmrCodigo;
    }

    
    @Column(name="jnmr_nombre", nullable=false, length=25)
    public String getJnmrNombre() {
        return this.jnmrNombre;
    }
    
    public void setJnmrNombre(String jnmrNombre) {
        this.jnmrNombre = jnmrNombre;
    }

    
    @Column(name="jnmr_estado", nullable=false)
    public boolean isJnmrEstado() {
        return this.jnmrEstado;
    }
    
    public void setJnmrEstado(boolean jnmrEstado) {
        this.jnmrEstado = jnmrEstado;
    }

    
    @Column(name="jnmr_usuario_insert", nullable=false, length=50)
    public String getJnmrUsuarioInsert() {
        return this.jnmrUsuarioInsert;
    }
    
    public void setJnmrUsuarioInsert(String jnmrUsuarioInsert) {
        this.jnmrUsuarioInsert = jnmrUsuarioInsert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnmr_fecha_insert", nullable=false, length=19)
    public Date getJnmrFechaInsert() {
        return this.jnmrFechaInsert;
    }
    
    public void setJnmrFechaInsert(Date jnmrFechaInsert) {
        this.jnmrFechaInsert = jnmrFechaInsert;
    }

    
    @Column(name="jnmr_usuario_update", nullable=false, length=50)
    public String getJnmrUsuarioUpdate() {
        return this.jnmrUsuarioUpdate;
    }
    
    public void setJnmrUsuarioUpdate(String jnmrUsuarioUpdate) {
        this.jnmrUsuarioUpdate = jnmrUsuarioUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jnmr_fecha_update", nullable=false, length=19)
    public Date getJnmrFechaUpdate() {
        return this.jnmrFechaUpdate;
    }
    
    public void setJnmrFechaUpdate(Date jnmrFechaUpdate) {
        this.jnmrFechaUpdate = jnmrFechaUpdate;
    }




}


